const host = process.env.DB_HOST;
const port = process.env.DB_PORT;
const user = process.env.DB_USER;
const pass = process.env.DB_PASSWORD;
const db = process.env.DB_SCHEMA;
const env = process.env.NODE_ENV;
const ci = process.env.CI;
const wf = process.env.GITHUB_WORKFLOW;
const id = process.env.GITHUB_RUN_ID;
console.log( '\n--------------------------------' );
console.log( '--------------------------------' );
console.log( '--------------------------------' );
console.log( `HOST: ${host}` );
console.log( `PORT: ${port}` );
console.log( `USER: ${user}` );
console.log( `PASS: ${pass}` );
console.log( `DB: ${db}` );
console.log( `ENV: ${env}` );
console.log( `CI: ${ci}` );
console.log( `WF: ${wf}` );
console.log( `ID: ${id}` );
console.log( '--------------------------------' );
console.log( '--------------------------------' );
console.log( '--------------------------------\n' );